### ISSUE TITLE
Test_Model Issue

### ISSUE THREAD

**Issue by BrandonChen1** [axr6077/TigerAssist#1]
if cnt.any != None:
AttributeError: 'NoneType' object has no attribute 'any'

**Comment by axr6077** [comment]
Use if `cnt.any() != None:`
    ...

Its because the camera isn't reading inputs in the input rectangle so the numpy array is empty hence raising this AttributeError. Make sure the webcam is reading inputs when initialized.

**Comment by BrandonChen1** [comment]
Can't check where the input source is.

**Comment by axr6077** [comment]
Fix coming soon
