### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by BrandonChen1** [axr6077/TigerAssist#6]
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by axr6077** [comment]
Generate a python wrapper depending on your version with SWIG and GCC. Ref: https://support.leapmotion.com/hc/en-us/articles/223784048

**Comment by axr6077** [comment]
Update: Go to python-wrapper directory released in commit ac8fa54441a356df5e07b372cd6c480304b1478a
Run the command:
sh build_leap_python3.sh

Issue arose because incompatible python versions for leap (official src supports 2.7)
